project:
  host: "http://localhost:8081"
  listById: "/project/employee/"

spring:
  datasource:
    url: jdbc:h2:mem:empdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

